import json
import os
import shlex
import shutil
import subprocess
import zipfile
from pathlib import Path


DEFAULT_WORKER_IMAGE = "am009/latexdiff-web-worker"
WORKSPACE_MARKER = ".pub_assist_latexdiff_workspace"

DEFAULT_SUBMISSION_STYLE = {
    "new_text": {
        "color": [0, 0, 255],
        "style": "underline_wave",
    },
    "old_text": {
        "color": [255, 0, 0],
        "style": "strikeout",
    },
}


class LatexdiffWorkerError(RuntimeError):
    """Raised when the git-latexdiff-web Docker worker fails."""


class LocalLatexdiffError(RuntimeError):
    """Raised when local latexdiff or LaTeX compilation fails."""


def _as_path(path):
    return Path(path).expanduser().resolve()


def _zip_directory(source_dir, target_zip):
    source_dir = _as_path(source_dir)
    target_zip = _as_path(target_zip)

    with zipfile.ZipFile(target_zip, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(source_dir.rglob("*")):
            if path.is_file():
                archive.write(path, path.relative_to(source_dir).as_posix())


def _materialize_zip(source, target_zip):
    source_path = _as_path(source)
    target_zip = _as_path(target_zip)

    if not source_path.exists():
        raise FileNotFoundError(f"Input path does not exist: {source_path}")

    if source_path.is_dir():
        _zip_directory(source_path, target_zip)
    elif source_path.is_file() and source_path.suffix.lower() == ".zip":
        shutil.copy2(source_path, target_zip)
    else:
        raise ValueError(
            "Input must be a LaTeX project folder or an Overleaf-style .zip file: "
            f"{source_path}"
        )


def _extract_zip(zip_path, destination):
    destination = _as_path(destination)
    destination.mkdir(parents=True, exist_ok=True)

    with zipfile.ZipFile(_as_path(zip_path)) as archive:
        archive.extractall(destination)


def _copy_tree_contents(source, destination):
    source = _as_path(source)
    destination = _as_path(destination)
    destination.mkdir(parents=True, exist_ok=True)

    for item in source.iterdir():
        target = destination / item.name
        if item.is_dir():
            shutil.copytree(item, target, dirs_exist_ok=True)
        else:
            shutil.copy2(item, target)


def _run_command(command, cwd, use_cmd=False):
    run_command = ["cmd", "/c"] + command if use_cmd else command
    result = subprocess.run(
        run_command,
        cwd=str(cwd),
        text=True,
        encoding="utf-8",
        errors="replace",
        capture_output=True,
    )

    return {
        "command": format_command(run_command),
        "returncode": result.returncode,
        "stdout": result.stdout,
        "stderr": result.stderr,
    }


def _reset_workspace(workspace):
    marker = workspace / WORKSPACE_MARKER

    if not marker.exists():
        raise FileExistsError(
            f"Refusing to overwrite {workspace} because it was not created by this helper. "
            f"Choose an empty/new workspace_dir or manually remove the directory."
        )

    shutil.rmtree(workspace)


def build_config(main_tex, bib=None, style=None, other_cmdlines=""):
    """
    Build the config.json consumed by am009/git-latexdiff-web's worker image.

    style can be a latexdiff style string such as "UNDERLINE", a custom style
    dictionary, or None for Pub Assist's submission-oriented default.
    """
    return {
        "other_cmdlines": other_cmdlines or "",
        "style": DEFAULT_SUBMISSION_STYLE if style is None else style,
        "main_tex": main_tex,
        "bib": bib,
    }


def prepare_latexdiff_workspace(
    old_project,
    new_project,
    main_tex,
    workspace_dir="latexdiff_runs/current",
    bib=None,
    style=None,
    other_cmdlines="",
    overwrite=True,
):
    """
    Create the old.zip, new.zip, and config.json layout expected by the worker.

    old_project and new_project can each be either a project folder or a .zip.
    """
    workspace = _as_path(workspace_dir)

    if workspace.exists():
        if not overwrite:
            raise FileExistsError(
                f"Workspace already exists: {workspace}. Set overwrite=True to replace it."
            )
        _reset_workspace(workspace)

    workspace.mkdir(parents=True, exist_ok=True)
    (workspace / WORKSPACE_MARKER).write_text(
        "Generated by Pub Assist latexdiff_web.py.\n",
        encoding="utf-8",
    )

    old_zip = workspace / "old.zip"
    new_zip = workspace / "new.zip"
    config_path = workspace / "config.json"

    _materialize_zip(old_project, old_zip)
    _materialize_zip(new_project, new_zip)

    config = build_config(
        main_tex=main_tex,
        bib=bib,
        style=style,
        other_cmdlines=other_cmdlines,
    )
    config_path.write_text(json.dumps(config, indent=2), encoding="utf-8")

    return {
        "workspace": str(workspace),
        "old_zip": str(old_zip),
        "new_zip": str(new_zip),
        "config_json": str(config_path),
        "config": config,
        "docker_command": docker_worker_command(workspace),
    }


def docker_worker_command(workspace_dir, image=DEFAULT_WORKER_IMAGE, debug=False):
    workspace = _as_path(workspace_dir)
    command = ["docker", "run", "--rm"]

    if debug:
        command.extend(["-e", "DEBUG=1"])

    command.extend(["-v", f"{workspace}:/work", image])
    return command


def format_command(command):
    command = [str(part) for part in command]

    if os.name == "nt":
        return subprocess.list2cmdline(command)

    return " ".join(shlex.quote(part) for part in command)


def run_latexdiff_worker(
    workspace_dir,
    image=DEFAULT_WORKER_IMAGE,
    debug=False,
    pull_image=False,
    use_cmd=False,
    check=True,
):
    """
    Run the Docker worker and return stdout, stderr, and expected output paths.
    """
    workspace = _as_path(workspace_dir)

    if pull_image:
        pull_command = ["docker", "pull", image]
        subprocess.run(["cmd", "/c"] + pull_command if use_cmd else pull_command, check=True)

    command = docker_worker_command(workspace, image=image, debug=debug)
    run_command = ["cmd", "/c"] + command if use_cmd else command
    result = subprocess.run(
        run_command,
        cwd=str(workspace),
        text=True,
        encoding="utf-8",
        errors="replace",
        capture_output=True,
    )

    output = {
        "command": format_command(run_command),
        "returncode": result.returncode,
        "stdout": result.stdout,
        "stderr": result.stderr,
        "diff_pdf": str(workspace / "diff.pdf"),
        "diff_project": str(workspace / "git-latexdiff" / "new"),
    }

    if check and result.returncode != 0:
        raise LatexdiffWorkerError(
            "git-latexdiff-web worker failed with exit code "
            f"{result.returncode}.\n\nCommand:\n{output['command']}\n\n"
            f"stdout:\n{result.stdout}\n\nstderr:\n{result.stderr}"
        )

    return output


def run_local_latexdiff(
    workspace_dir,
    latexdiff_executable="latexdiff",
    pdflatex_executable="pdflatex",
    bibtex_executable="bibtex",
    biber_executable="biber",
    compile_pdf=True,
    use_cmd=False,
    check=True,
):
    """
    Run latexdiff locally using MiKTeX/TeX Live tools instead of Docker.

    The workspace must already contain old.zip, new.zip, and config.json from
    prepare_latexdiff_workspace().
    """
    workspace = _as_path(workspace_dir)
    config_path = workspace / "config.json"
    config = json.loads(config_path.read_text(encoding="utf-8"))

    main_tex = config["main_tex"]
    bib = config.get("bib")
    style = config.get("style")
    other_cmdlines = config.get("other_cmdlines") or ""

    local_dir = workspace / "local-latexdiff"
    if local_dir.exists():
        shutil.rmtree(local_dir)

    old_dir = local_dir / "old"
    new_dir = local_dir / "new"
    build_dir = local_dir / "build"

    _extract_zip(workspace / "old.zip", old_dir)
    _extract_zip(workspace / "new.zip", new_dir)

    # Compile against new files, but keep old-only assets available for deleted floats.
    _copy_tree_contents(old_dir, build_dir)
    _copy_tree_contents(new_dir, build_dir)

    old_tex = old_dir / main_tex
    new_tex = new_dir / main_tex
    diff_tex = build_dir / main_tex

    if not old_tex.exists():
        raise FileNotFoundError(f"Old project does not contain {main_tex}: {old_tex}")
    if not new_tex.exists():
        raise FileNotFoundError(f"New project does not contain {main_tex}: {new_tex}")

    latexdiff_command = [latexdiff_executable, "--flatten"]

    if style is None or isinstance(style, dict):
        latexdiff_command.append("--type=UNDERLINE")
    elif isinstance(style, str):
        latexdiff_command.append(f"--type={style}")

    if other_cmdlines:
        latexdiff_command.extend(shlex.split(other_cmdlines))

    latexdiff_command.extend([str(old_tex), str(new_tex)])

    run_latexdiff_command = ["cmd", "/c"] + latexdiff_command if use_cmd else latexdiff_command
    latexdiff_result = subprocess.run(
        run_latexdiff_command,
        cwd=str(workspace),
        text=True,
        encoding="utf-8",
        errors="replace",
        capture_output=True,
    )

    if latexdiff_result.stdout:
        diff_tex.parent.mkdir(parents=True, exist_ok=True)
        diff_tex.write_text(latexdiff_result.stdout, encoding="utf-8")

    commands = [
        {
            "command": format_command(run_latexdiff_command),
            "returncode": latexdiff_result.returncode,
            "stdout": latexdiff_result.stdout,
            "stderr": latexdiff_result.stderr,
        }
    ]

    if latexdiff_result.returncode != 0:
        output = {
            "returncode": latexdiff_result.returncode,
            "commands": commands,
            "stdout": latexdiff_result.stdout,
            "stderr": latexdiff_result.stderr,
            "diff_pdf": str(workspace / "diff.pdf"),
            "diff_project": str(build_dir),
            "diff_tex": str(diff_tex),
        }

        if check:
            raise LocalLatexdiffError(
                "local latexdiff failed.\n\nCommand:\n"
                f"{commands[0]['command']}\n\nstderr:\n{latexdiff_result.stderr}"
            )

        return output

    pdf_path = build_dir / f"{Path(main_tex).stem}.pdf"

    if compile_pdf:
        main_file_name = Path(main_tex).name
        compile_dir = diff_tex.parent
        compile_sequence = [
            [pdflatex_executable, "-interaction=nonstopmode", "-halt-on-error", main_file_name],
        ]

        if bib == "bibtex":
            compile_sequence.append([bibtex_executable, Path(main_tex).stem])
        elif bib == "biber":
            compile_sequence.append([biber_executable, Path(main_tex).stem])

        compile_sequence.extend([
            [pdflatex_executable, "-interaction=nonstopmode", "-halt-on-error", main_file_name],
            [pdflatex_executable, "-interaction=nonstopmode", "-halt-on-error", main_file_name],
        ])

        for command in compile_sequence:
            result = _run_command(command, cwd=compile_dir, use_cmd=use_cmd)
            commands.append(result)

            if result["returncode"] != 0:
                output = {
                    "returncode": result["returncode"],
                    "commands": commands,
                    "stdout": result["stdout"],
                    "stderr": result["stderr"],
                    "diff_pdf": str(workspace / "diff.pdf"),
                    "diff_project": str(build_dir),
                    "diff_tex": str(diff_tex),
                }

                if check:
                    raise LocalLatexdiffError(
                        "local LaTeX compilation failed.\n\nCommand:\n"
                        f"{result['command']}\n\nstdout:\n{result['stdout']}\n\nstderr:\n{result['stderr']}"
                    )

                return output

        if pdf_path.exists():
            shutil.copy2(pdf_path, workspace / "diff.pdf")

    output = {
        "returncode": 0 if (not compile_pdf or (workspace / "diff.pdf").exists()) else 1,
        "commands": commands,
        "stdout": "\n".join(command["stdout"] for command in commands if command["stdout"]),
        "stderr": "\n".join(command["stderr"] for command in commands if command["stderr"]),
        "diff_pdf": str(workspace / "diff.pdf"),
        "diff_project": str(build_dir),
        "diff_tex": str(diff_tex),
    }

    if check and output["returncode"] != 0:
        raise LocalLatexdiffError("local latexdiff finished without creating diff.pdf")

    return output
