import json
import shlex
import shutil
import subprocess
import zipfile
from pathlib import Path


DEFAULT_WORKER_IMAGE = "am009/latexdiff-web-worker"
WORKSPACE_MARKER = ".pub_assist_latexdiff_workspace"

DEFAULT_SUBMISSION_STYLE = {
    "new_text": {
        "color": [0, 0, 255],
        "style": "underline_wave",
    },
    "old_text": {
        "color": [255, 0, 0],
        "style": "strikeout",
    },
}


class LatexdiffWorkerError(RuntimeError):
    """Raised when the git-latexdiff-web Docker worker fails."""


def _as_path(path):
    return Path(path).expanduser().resolve()


def _zip_directory(source_dir, target_zip):
    source_dir = _as_path(source_dir)
    target_zip = _as_path(target_zip)

    with zipfile.ZipFile(target_zip, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(source_dir.rglob("*")):
            if path.is_file():
                archive.write(path, path.relative_to(source_dir).as_posix())


def _materialize_zip(source, target_zip):
    source_path = _as_path(source)
    target_zip = _as_path(target_zip)

    if not source_path.exists():
        raise FileNotFoundError(f"Input path does not exist: {source_path}")

    if source_path.is_dir():
        _zip_directory(source_path, target_zip)
    elif source_path.is_file() and source_path.suffix.lower() == ".zip":
        shutil.copy2(source_path, target_zip)
    else:
        raise ValueError(
            "Input must be a LaTeX project folder or an Overleaf-style .zip file: "
            f"{source_path}"
        )


def _reset_workspace(workspace):
    marker = workspace / WORKSPACE_MARKER

    if not marker.exists():
        raise FileExistsError(
            f"Refusing to overwrite {workspace} because it was not created by this helper. "
            f"Choose an empty/new workspace_dir or manually remove the directory."
        )

    shutil.rmtree(workspace)


def build_config(main_tex, bib=None, style=None, other_cmdlines=""):
    """
    Build the config.json consumed by am009/git-latexdiff-web's worker image.

    style can be a latexdiff style string such as "UNDERLINE", a custom style
    dictionary, or None for Pub Assist's submission-oriented default.
    """
    return {
        "other_cmdlines": other_cmdlines or "",
        "style": DEFAULT_SUBMISSION_STYLE if style is None else style,
        "main_tex": main_tex,
        "bib": bib,
    }


def prepare_latexdiff_workspace(
    old_project,
    new_project,
    main_tex,
    workspace_dir="latexdiff_runs/current",
    bib=None,
    style=None,
    other_cmdlines="",
    overwrite=True,
):
    """
    Create the old.zip, new.zip, and config.json layout expected by the worker.

    old_project and new_project can each be either a project folder or a .zip.
    """
    workspace = _as_path(workspace_dir)

    if workspace.exists():
        if not overwrite:
            raise FileExistsError(
                f"Workspace already exists: {workspace}. Set overwrite=True to replace it."
            )
        _reset_workspace(workspace)

    workspace.mkdir(parents=True, exist_ok=True)
    (workspace / WORKSPACE_MARKER).write_text(
        "Generated by Pub Assist latexdiff_web.py.\n",
        encoding="utf-8",
    )

    old_zip = workspace / "old.zip"
    new_zip = workspace / "new.zip"
    config_path = workspace / "config.json"

    _materialize_zip(old_project, old_zip)
    _materialize_zip(new_project, new_zip)

    config = build_config(
        main_tex=main_tex,
        bib=bib,
        style=style,
        other_cmdlines=other_cmdlines,
    )
    config_path.write_text(json.dumps(config, indent=2), encoding="utf-8")

    return {
        "workspace": str(workspace),
        "old_zip": str(old_zip),
        "new_zip": str(new_zip),
        "config_json": str(config_path),
        "config": config,
        "docker_command": docker_worker_command(workspace),
    }


def docker_worker_command(workspace_dir, image=DEFAULT_WORKER_IMAGE, debug=False):
    workspace = _as_path(workspace_dir)
    command = ["docker", "run", "--rm"]

    if debug:
        command.extend(["-e", "DEBUG=1"])

    command.extend(["-v", f"{workspace}:/work", image])
    return command


def format_command(command):
    return " ".join(shlex.quote(str(part)) for part in command)


def run_latexdiff_worker(
    workspace_dir,
    image=DEFAULT_WORKER_IMAGE,
    debug=False,
    pull_image=False,
    check=True,
):
    """
    Run the Docker worker and return stdout, stderr, and expected output paths.
    """
    workspace = _as_path(workspace_dir)

    if pull_image:
        subprocess.run(["docker", "pull", image], check=True)

    command = docker_worker_command(workspace, image=image, debug=debug)
    result = subprocess.run(
        command,
        cwd=str(workspace),
        text=True,
        capture_output=True,
    )

    output = {
        "command": format_command(command),
        "returncode": result.returncode,
        "stdout": result.stdout,
        "stderr": result.stderr,
        "diff_pdf": str(workspace / "diff.pdf"),
        "diff_project": str(workspace / "git-latexdiff" / "new"),
    }

    if check and result.returncode != 0:
        raise LatexdiffWorkerError(
            "git-latexdiff-web worker failed with exit code "
            f"{result.returncode}.\n\nCommand:\n{output['command']}\n\n"
            f"stdout:\n{result.stdout}\n\nstderr:\n{result.stderr}"
        )

    return output
